### PR TITLE
Add support for ternary operators

### PR DESCRIPTION
**Pull request by feuerbach**
Hey Mark,

The ternary operator is a common language construct, so it would be nice to support it here. (I originally implemented this for patterns in tasty, and now we also needed this for one of the clients.)

### CODE REVIEW

**Comment by mrkkrp** [comment]
I’m on vacation right now but I’ll review it once I get back to Paris.

**Comment by mrkkrp** [comment]
This looks good to me. One problem is that I'd like to have some tests for the new feature. `parser-combinators` have been historically tested in Megaparsec's test suite because they do not make much sense without some parsing library to be used with, but `parser-combinators` as a package cannot depend on `megaparsec` because the latter itself depends on `parser-combinators`. I think now it's the time to move the tests from Megaparsec's test suite to this package, but I've not yet decided exactly how. One way perhaps is to write a minimal Parsec-like toy parser as part of the test suite and then test using that. What do you think?

Another thing is that this could be considered a breaking change because it adds a new data constructor and thus potentially may introduce incomplete pattern-matches. Although I don't think there is a lot of code that uses the `Operator` data type for something other than construction of operator tables, but still. What is your opinion, should we bump the version to `2.0.0`?

**Comment by feuerbach** [comment]
> but parser-combinators as a package cannot depend on megaparsec because the latter itself depends on parser-combinators

One way around this is to add a separate package that would only have the tests. That package then could live in this repo but depend on both megaparsec and parser-combinators. This is what I do for tasty, when I need the tasty tests to depend on tasty-hunit, which in turn depends on tasty: https://github.com/feuerbach/tasty/tree/master/core-tests

**Comment by feuerbach** [comment]
> What is your opinion, should we bump the version to 2.0.0?

You could bump to 1.1.0, but yeah, it should be a major bump it seems.

**Comment by mrkkrp** [comment]
I'll work on fixing this issue with testing and then return to this PR, because it looks to me that testing is a prerequisite for merging changes like this.

**Comment by mrkkrp** [comment]
One disadvantage of the method, it appears, that users won't be able to test the package locally because the package will come without test suite. To solve that, we could publish the package containing the tests separately. Then, whenever a change or addition is made to the main package, the testing companion package should also get a new release. This increases the maintenance burden but seems to solve the issue.

**Comment by feuerbach** [comment]
> One disadvantage of the method, it appears, that users won't be able to test the package locally because the package will come without test suite.

Perhaps I misunderstand what you're saying, but users are able to test the package locally, just using a somewhat different workflow. Instead of running `{cabal,stack} test`, they'll need to do `{cabal,stack} build` and then run the executable manually. This workflow could be documented in the readme, say.

**Comment by mrkkrp** [comment]
What I meant is that if you get `tasty` from Hackage, it doesn't come with a test suite:

https://hackage.haskell.org/package/tasty-1.2.1/src/

And afaik the test suite only exists in the git repo, unversioned and "disconnected" from published package.

**Comment by feuerbach** [comment]
Ok, right. But I'm having a hard time imagining someone wanting to run the tests and not having a checked out repo (let alone not willing to check it out).

**Comment by mrkkrp** [comment]
One example is Stackage. They run test suites and sometimes they catch things, e.g. breakage because of some update in a dependency. It's sort of useful. That's why I'm going to publish test package together with the libraries.

**Comment by mrkkrp** [comment]
I added the test suite package called `parser-combinators-tests` and the tests are run on CI now. I also rebased this PR. Please add the corresponding tests and describe the new feature in the changelog.

**Comment by mrkkrp** [comment]
Are you still intending to bring this one to completion or should I pick this up?

**Comment by feuerbach** [comment]
Sure, I just don't know when I'll have the time to work on this next — could be a couple of weeks. If you feel like doing this yourself, go for it.

**Comment by mrkkrp** [comment]
> If you feel like doing this yourself, go for it.

**Comment by feuerbach** [comment]
Hi Mark, I've updated the tests and added a changelog entry.

**Pull request merged**
